# Generated by Django 5.0.6 on 2024-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
